[package]
name = "meme_generator"
version = "0.1.0"
edition = "2021"

[dependencies]
skia-safe = { version = "0.80", features = ["default", "textlayout"] }
gif = "0.13"
directories = "5.0"
tokio = { version = "1.41", features = ["full"] }
reqwest = { version = "0.11", features = ["json", "stream"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
clap = "4.5"
sha2 = "0.9"
indicatif = "0.16"
toml = "0.8"
ctor = "0.2"
log = "0.4"
chrono = { version = "0.4", features = ["serde"] }
meme_options_derive = { path = "../meme_options_derive" }
