[package]
name = "meme_generator_cli"
version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
clap = { version = "4.5", features = ["string"] }
infer = "0.16"
serde_json = "1.0"
tokio = { version = "1.42", optional = true }

meme_generator = { path = "../meme_generator" }
meme_generator_server = { path = "../meme_generator_server", optional = true }

[features]
default = []
server = ["dep:meme_generator_server", "dep:tokio"]

[[bin]]
name = "meme"
path = "src/main.rs"
